huds_refresh_interval_ticks: 15
huds_high_frequency_refresh_interval_ticks: 1
legacy_1_18_and_lower_textures: false
money:
  enabled: true
  offset: 91
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  papi_placeholder: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
compass:
  enabled: true
  offset: -9
  worlds:
    - world
    - world_nether
    - world_the_end
quiver:
  enabled: true
  offset:
    normal: -96
    when_offhand_shown: -124
  content_update_ticks: 100
  worlds:
    - world
    - world_nether
    - world_the_end
arrow_target:
  enabled: true
  offset: -98
  worlds:
    - world
    - world_nether
    - world_the_end
lang:
  hud_not_found: "&6Hud not found!"
  wrong_usage: "&cWrong command usage."
  destination_set: "&aDestination set."
  destination_removed: "&7Destination removed."
log:
  debug: false
